# Generated by Django 3.0.3 on 2021-09-15 19:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoproject',
            name='description',
        ),
        migrations.AddField(
            model_name='autoproject',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
