# Generated by Django 3.0.3 on 2021-09-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210916_0058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
